# Default values for skaffold-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 2
image: skaffold-helm:latest
service:
  type: ClusterIP
  externalPort: 3000
  internalPort: 3000
